### PR TITLE
Update proxy renewal make rfc default.

### PR DESCRIPTION
**Pull request by aaarora**
Added '-rfc' to CMD in voms_proxy_fake()

### CODE REVIEW

**Comment by efajardo** [comment]
@mambelli can you review this. All proxies should come as RFC anyway but this is definetly a bug

**Comment by efajardo** [comment]
@brianhlin I am tagging you since you developed this. @aaarora is a student of mine working on containarizing GWMS parts

**Comment by brianhlin** [comment]
I always forget whether we want RFC or not... I seem to remember @rynge knowing more about this but I could be completely wrong...

**Comment by efajardo** [comment]
we always want RFC

**Comment by rynge** [comment]
We use legacy proxies for OSG VO - but probably because that is what gwms proxy script creates.

At some point we had issues with RFC ones on some European CEs.

**Comment by brianhlin** [comment]
@efajardo it sounds like then we need to add this as an option to the configuration so that operators can decide which proxies are generated as RFC vs non-RFC, defaulting to the latter.

**Comment by brianhlin** [comment]
@rynge perhaps we should go with RFC as the default and lean on those European sites to accept RFC proxies?

**Comment by rynge** [comment]
Sure, I have no preference.

**Comment by brianhlin** [comment]
In that case, @efajardo, I'm on board with this change

**Comment by efajardo** [comment]
@mambelli so can we merge this?

**Comment by mambelli** [comment]
The Fermilab one is still the main repo. Changes are in b3fd8c1aa7d1d0b53e56029ef63928b3c21b5b49
I added also a comma that was missing.

**Comment by efajardo** [comment]
@mambelli in fact there is a mistake here. If we use `-rfc` we also have to use `-pathlength 20` or some big number.

**Pull request closed without merging**
