### PR TITLE
Add an option to clear conflicting variables in containers environment

### LINKED ISSUE #341: Add an option to clear conflicting variables in GLIDEIN_SINGULARITY_ENV
**Is your feature request related to a problem? Please describe.**
Stageout on el8 at some CMS sites is failing because of some conflicting GFAL_* variables. The ones set in the host for el7 leaks into the el8 container and screw things up.

**Describe the solution you'd like**
It would be nice to have an option to clear conflicting variables. GLIDEIN_SINGULARITY_ENV already has clearpaths, I think we should add clearconflicts and then use GLIDEIN_SINGULARITY_ENV_CONFLICTS to get the list of variables to clear.

**Info (please complete the following information):**

-   Priority: Priority level for this feature [critical]
-   Stakeholders: Concerned stakeholder(s) [CMS]
-   Components: The affected component, if any, from this feature [glidein]

### PR DESCRIPTION
**Pull request by mmascher**
Using the env variable GLIDEIN_CONTAINER_ENV_CLEARLIST to clear env variables. 
Fixes #341

### CODE REVIEW

**Comment by mambelli** [comment]
Rebased to master
Changed the var name to GLIDEIN_CONTAINER_ENV_CLEARLIST (it is not singularity specific, all new variables should use GLIDEIN_CONTAINER_...)
Fixed a couple of bugs (unit test, quotes blocking for)
TODO about unclear line
Specific unit test should be added

**Comment by mmascher** [comment]
Tested this and it does not work. The invocation of `env_clear` is done inside parenthesis: [$(env_clear)](https://github.com/glideinWMS/glideinwms/blob/master/creation/web_base/singularity_lib.sh#L2031)

Therefore, as confirmed by the test script below, the velue of the variable is not going to be unset. Possibly, these [two lines](https://github.com/glideinWMS/glideinwms/blob/master/creation/web_base/singularity_lib.sh#L741-L742) are not working as well in the current code and it is why we are clearing them separately [here](https://github.com/glideinWMS/glideinwms/blob/master/creation/web_base/singularity_lib.sh#L2006-L2028)?

Anyway, for the time being I am putting the clearlist stuff in a separate function and giving it a try (see the commit).

Test script:
```
export A=0
marco@marco-LEGION5:~$ cat tmp.sh 
test() {
	unset A
}

echo $A
B=$(test)
#test
echo $A
marco@marco-LEGION5:~$ sh tmp.sh 
0
0
marco@marco-LEGION5:~$ vim tmp.sh 
marco@marco-LEGION5:~$ sh tmp.sh 
0

marco@marco-LEGION5:~$ cat tmp.sh 
test() {
	unset A
}

echo $A
#B=$(test)
test
echo $A
```

**Comment by mmascher** [comment]
My test were successful with the latest commit

**Comment by mambelli** [comment]
I generalized the functions to take an argument so I could add a unit test for them

**Comment by mambelli** [comment]
Did a force push after rebase to clear merge conflicts (in CHANGELOG.md)

**Review by mambelli — APPROVED** [review]

**Pull request merged**
