### PR TITLE
Fix exception duting completed stats computation. Fixes #155

### LINKED ISSUE #155: Completed stats are missing after 3.9.5 upgraded
One of the monitoring pages was showing condor failing to start and triggering alarm for the UCSD factory after the upgrade. It turns out that the `rrd_Log_Completed.xml` file was not containing correct information. After some investigation I found out this was the cause of the issue:

```
>>> from glideinwms.factory.glideFactoryLogParser import extractLogData
>>> extractLogData("/var/log/gwms-factory/client/user_fecmsglobal/glidein_gfactory_instance/entry_CMSHTPC_T2_AT_Vienna_ce-1/job.10034598.7.out")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/glideinwms/factory/glideFactoryLogParser.py", line 376, in extractLogData
    validate_re = ELD_RC_VALIDATE_END.search(buf, buf_idx)
TypeError: cannot use a string pattern on a bytes-like object
```

I fixed it by adding a `.read().decode("utf-8")` to the buffer. It seems to work without adding any cost to the performances. Still keeping an eye on it.

### PR DESCRIPTION
**Pull request by mmascher**

### CODE REVIEW

**Comment by mmascher** [comment]
I see we have a dir named `unittests/fixtures/factory/log/client/` in the repo. It is empty. Is it supposed to contain glidein logfiles that can be used for unit tests? I was thinking of adding a real(production) glidein stdout logfile and adding a unit test.

**Comment by mmascher** [comment]
I just closed https://github.com/glideinWMS/glideinwms/pull/164 that preceeded this one.

**Comment by mambelli** [comment]
Changers satisfy the suggestions in PR #160.
`unittests/fixtures/factory/log/client/` and a subdirectory under it are the right directory for the log file as discussed in the meeting today. Waiting for the unit test before approving and merging.

**Comment by mmascher** [comment]
@mambelli I run the test on my machine and I could not replicate the issue. Could it be related to a different version of the system `m2crypto` library? I have '0.35.2' on my machine.

I see the output of the unit test is saved here `output/gwms.LOCAL.pyunittest.d/gwms.LOCAL.pyunittest.d.test_lib_symCrypto.txt` but I could not find out how to access it. Can you help me? :)

**Pull request closed without merging**
