### PR TITLE
the workdir creation was failing at some sites

### PR DESCRIPTION
**Pull request by efajardo**

### CODE REVIEW

**Comment by mambelli** [comment]
@efajardo What happens is the directory creation fails? SINGULARITY_WORKDIR is undefined. Is that OK for the rest of the code and to continue?

**Comment by efajardo** [comment]
@mambelli yes and is not in anyway worst where it is now. Where we get this errors in the jobs standard errors:

{noformat}
/data1/condor_local/execute/dir_126570/glide_R0L14U/tmp/singularity-work.141810/tmp: mkdir /data1/condor_local/execute/dir_126570/glide_R0L14U/tmp/singularity-work.141810/tmp: no such file or directory
{noformat}

So at least this is better. The solution came from @rynge

**Comment by mambelli** [comment]
I opened a ticket to track the issue: https://cdcvs.fnal.gov/redmine/issues/22998
and committed the changes to branch v34/22998
I applied the changes also to the singularity_script_example.sh

**Comment by mambelli** [comment]
@efajardo Do you think changes in branch v34/22998 solve your pull request proposal?

**Comment by mambelli** [comment]
An improved version of the proposed code was added to v34/22998 off branch_v3_4 and merged in branch_v3_4 after review.
It will be merged into master after the release of 3.4.6
Closing the pull request

**Pull request closed without merging**
